### ISSUE TITLE
Add Coinbase API

### ISSUE THREAD

**Issue by arabacibahadir** [arabacibahadir/sup-res#16]
## Problem
We need to integrate with the Coinbase API to retrieve and update cryptocurrency information.

## Solution
We can add integration with the Coinbase API to our application by using their API and SDK.
https://docs.cloud.coinbase.com/exchange/docs/welcome

## Expected outcome
Our application will be able to retrieve and update cryptocurrency information from Coinbase.

**Comment by Usernamethoma** [comment]
@arabacibahadir We'd be happy to look into this for you.
Kindly file a support ticket here
https://forms.gle/xABEcR5MwDBJAm1c6

**Comment by arabacibahadir** [comment]
I decided to halt the development of this issue and focus on other issues because I believe it is unnecessary for the time being, and "binance.us" can be used instead of coinbase.
