### ISSUE TITLE
accept a csv file of coins to create chart

### ISSUE THREAD

**Issue by ocmich74** [arabacibahadir/sup-res#20]
I would love to see this project updated to where it has the option to accept a csv file that has the coin name and timeframe to create the chart automatically, instead of having to enter one at a time.

**Comment by arabacibahadir** [comment]
Hi,
Thanks for good idea. I'll look into how I can do it and I will consider its effectiveness.

**Comment by arabacibahadir** [comment]
https://github.com/arabacibahadir/sup-res/commit/220879e379739e0a293d4ccb978950172c9fde73
From now, you can run the `../miniscripts/multiple_run.py` script to generate multiple charts. Simply, just make changes to the `../miniscripts/coin_list.csv` as needed.
