### ISSUE TITLE
Error Install Debian 64bits

### ISSUE THREAD

**Issue by lgcambero** [arabacibahadir/sup-res#29]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
crackmapexec 5.4.0 requires aioconsole<0.4.0,>=0.3.3, but you have aioconsole 0.3.1 which is incompatible.                                                                      
crackmapexec 5.4.0 requires minikerberos==0.3.3, but you have minikerberos 0.3.5 which is incompatible.                                                                         
crackmapexec 5.4.0 requires neo4j<5.0.0,>=4.1.1, but you have neo4j 5.2.dev0 which is incompatible.                                                                             
crackmapexec 5.4.0 requires pypsrp<0.8.0,>=0.7.0, but you have pypsrp 0.5.0 which is incompatible.                                                                              
crackmapexec 5.4.0 requires xmltodict<0.13.0,>=0.12.0, but you have xmltodict 0.13.0 which is incompatible.

**Comment by lgcambero** [comment]
ERROR: Could not find a version that satisfies the requirement kaleido==0.1.0.post1 (from versions: 0.0.1rc3, 0.0.1rc4, 0.0.1rc5, 0.0.1rc6, 0.0.1rc8, 0.0.1rc9, 0.0.1, 0.0.2, 0.0.3, 0.0.3.post1, 0.1.0a2, 0.1.0a3, 0.1.0, 0.2.0rc1, 0.2.0, 0.2.1)
ERROR: No matching distribution found for kaleido==0.1.0.post1

**Comment by arabacibahadir** [comment]
Hello,
Thanks for this issue. Setting up to to `pip install --upgrade kaleido=0.1.0` or `pip install --upgrade kaleido=0.2.1` should work. I can't test right now on debian. If this solves your problem could you please let me know if it got fixed?

**Comment by lgcambero** [comment]
Yes, solved update requeriments.txt:

kaleido==0.2.1

Tks!!, good tool!! Congratulations!!
