### ISSUE TITLE
Telegram Support

### ISSUE THREAD

**Issue by Zmizo** [arabacibahadir/sup-res#6]
Hi , is it possible to add telegram support , so we can share this analysis to Telegram group or channel ? 

Thanks

**Comment by arabacibahadir** [comment]
Hi,
The project is still under development. Telegram support was behind my priority list, but as far as I can see it is needed. I'll speed up on this.

**Comment by arabacibahadir** [comment]
Hey, 
I have finished most of the project. Testing right now. Adding some commands and fixing some bugs, like resolution and price text bugs etc. If you can host, you can use bot right now. I will deploy bot on server soon, stay tuned.

![telegram](https://user-images.githubusercontent.com/32988819/147921441-18d5bdd6-e7f9-472b-92d2-23862a5563f3.png)

**Comment by Zmizo** [comment]
Hi ,

Thanks for the feedback , yes i will host and test

**Comment by Zmizo** [comment]
Hi , 
after testing , everything working great for the bot except supres btcusdt 1d 
this command doesnt work and i get error

 ( caused error [Errno 2] No such file or directory: 'py telegram_bot.py BTCUSDT 1D' )
